import Link from "next/link";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PrimeAlignJustify } from "./icons/menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <header className="bg-orange-600 h-16 sticky flex items-center justify-between">
          <Link href="/">
            <h1
              className="text-white mx-4 font-extrabold"
              style={{ fontFamily: "Impact, sans-serif" }}
            >
              サンプル！！ECサイト
            </h1>
          </Link>
          <PrimeAlignJustify className="text-4xl mr-5" />
        </header>
        <main className="overflow-auto flex-1">{children}</main>
      </body>
    </html>
  );
}
